replicaCount: 1

image:
  repository: ghcr.io/iamfittz/telegram-bot
  tag: latest
  pullPolicy: IfNotPresent

env:
  TELE_TOKEN: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"

service:
  port: 8080

resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
